-- 固定问题状态：0收集中、1待审核、2已通过、3已驳回、4已转知识、5已忽略。
-- LLM只生成标准回答草稿，最终状态必须由Java人工审核接口修改。
ALTER TABLE learning.learning_problem
    ADD COLUMN standard_answer TEXT,
    ADD COLUMN answer_provider VARCHAR(64),
    ADD COLUMN answer_model VARCHAR(128),
    ADD COLUMN answer_generated_at TIMESTAMPTZ,
    ADD COLUMN answer_generated_by VARCHAR(64),
    ADD COLUMN reviewed_by VARCHAR(64),
    ADD COLUMN reviewed_at TIMESTAMPTZ,
    ADD COLUMN review_comment VARCHAR(1000),
    ADD COLUMN rejection_reason VARCHAR(1000),
    ADD COLUMN review_version INTEGER NOT NULL DEFAULT 0;

ALTER TABLE learning.learning_problem
    ADD CONSTRAINT ck_learning_problem_review_version CHECK (review_version >= 0);

-- 每次生成、编辑、通过、驳回和忽略都追加一条记录，便于追责和恢复历史答案。
CREATE TABLE learning.learning_problem_review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id BIGINT NOT NULL,
    action_type SMALLINT NOT NULL,
    status_before SMALLINT NOT NULL,
    status_after SMALLINT NOT NULL,
    answer_snapshot TEXT,
    comment VARCHAR(1000),
    operator_id VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_learning_problem_review_problem FOREIGN KEY (problem_id)
        REFERENCES learning.learning_problem (id),
    CONSTRAINT ck_learning_problem_review_action CHECK (action_type IN (1, 2, 3, 4, 5)),
    CONSTRAINT ck_learning_problem_review_status_before CHECK (status_before IN (0, 1, 2, 3, 4, 5)),
    CONSTRAINT ck_learning_problem_review_status_after CHECK (status_after IN (0, 1, 2, 3, 4, 5))
);

CREATE INDEX idx_learning_problem_review_problem
    ON learning.learning_problem_review (problem_id, created_at DESC, id DESC);

COMMENT ON COLUMN learning.learning_problem.status IS
    '0收集中、1待审核、2已通过、3已驳回、4已转知识、5已忽略';
COMMENT ON COLUMN learning.learning_problem.standard_answer IS 'LLM生成并由人工编辑审核的标准回答草稿';
COMMENT ON TABLE learning.learning_problem_review IS '问题标准回答和人工审核的不可变操作历史';
