-- 问题审核可以产出FAQ知识或确定性Tool路由；0未选择、1 FAQ、2 Tool。
ALTER TABLE learning.learning_problem
    ADD COLUMN resolution_type SMALLINT NOT NULL DEFAULT 0,
    ADD COLUMN target_tool_name VARCHAR(128),
    ADD COLUMN route_published_at TIMESTAMPTZ;

-- V16之前只有FAQ审核产物；保留已有“已通过/已转知识”数据的原行为。
UPDATE learning.learning_problem
SET resolution_type = 1
WHERE status IN (2, 4);

ALTER TABLE learning.learning_problem
    ADD CONSTRAINT ck_learning_problem_resolution_type
        CHECK (resolution_type IN (0, 1, 2)),
    ADD CONSTRAINT ck_learning_problem_tool_resolution
        CHECK (
            (resolution_type = 2 AND target_tool_name IS NOT NULL)
            OR (resolution_type <> 2)
        );

-- 一个审核问题可以发布多条真实表达；标准化Hash在租户内唯一，避免同一句话执行不同Tool。
CREATE TABLE learning.exact_tool_route (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
    original_expression TEXT NOT NULL,
    normalized_expression VARCHAR(500) NOT NULL,
    expression_hash CHAR(64) NOT NULL,
    tool_name VARCHAR(128) NOT NULL,
    source_problem_id BIGINT NOT NULL,
    status SMALLINT NOT NULL DEFAULT 1,
    sync_status SMALLINT NOT NULL DEFAULT 0,
    retry_count INTEGER NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_error VARCHAR(1000),
    reviewed_by VARCHAR(64) NOT NULL,
    reviewed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    synced_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_exact_tool_route_problem FOREIGN KEY (source_problem_id)
        REFERENCES learning.learning_problem (id),
    CONSTRAINT uk_exact_tool_route_hash UNIQUE (tenant_id, expression_hash),
    CONSTRAINT ck_exact_tool_route_status CHECK (status IN (0, 1)),
    CONSTRAINT ck_exact_tool_route_sync_status CHECK (sync_status IN (0, 1, 2, 3)),
    CONSTRAINT ck_exact_tool_route_retry CHECK (retry_count >= 0)
);

CREATE INDEX idx_exact_tool_route_pending
    ON learning.exact_tool_route (sync_status, next_retry_at, id)
    WHERE status = 1 AND sync_status IN (0, 3);
CREATE INDEX idx_exact_tool_route_problem
    ON learning.exact_tool_route (source_problem_id, id);

CREATE TRIGGER trg_exact_tool_route_updated_at
    BEFORE UPDATE ON learning.exact_tool_route
    FOR EACH ROW EXECUTE FUNCTION business.set_updated_at();

COMMENT ON COLUMN learning.learning_problem.resolution_type IS
    '审核产物：0未选择、1 FAQ知识、2 Tool精确路由';
COMMENT ON TABLE learning.exact_tool_route IS
    '人工审核通过的真实表达到MCP Tool精确映射，同时承担Redis可靠同步状态';
