-- Java 业务服务拥有独立的 business schema。
-- Python 服务可以使用同一个 PostgreSQL 数据库，但不应直接修改这些表。
CREATE SCHEMA IF NOT EXISTS business;

CREATE TABLE IF NOT EXISTS business.business_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(64) NOT NULL,
    user_id VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    logistics_text VARCHAR(500),
    expected_progress VARCHAR(200),
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_business_order_no UNIQUE (order_no),
    CONSTRAINT ck_business_order_no_uppercase CHECK (order_no = UPPER(order_no)),
    CONSTRAINT ck_business_order_status CHECK (status IN (
        'CREATED', 'PAID', 'PROCESSING', 'SHIPPED', 'DELIVERED',
        'CANCELLED', 'REFUNDING', 'REFUNDED', 'CLOSED'
    ))
);

-- 查询条件固定包含 user_id 和 order_no；联合索引同时服务鉴权与订单定位。
CREATE INDEX IF NOT EXISTS idx_business_order_user_order
    ON business.business_order (user_id, order_no)
    WHERE deleted = FALSE;

CREATE TABLE IF NOT EXISTS business.tool_call_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id VARCHAR(64) NOT NULL,
    session_id VARCHAR(64) NOT NULL,
    tool_name VARCHAR(64) NOT NULL,
    user_id VARCHAR(64) NOT NULL,
    resource_id VARCHAR(64),
    result_code VARCHAR(64) NOT NULL,
    success BOOLEAN NOT NULL,
    duration_ms BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_tool_call_audit_duration CHECK (duration_ms >= 0)
);

CREATE INDEX IF NOT EXISTS idx_tool_call_audit_request_id
    ON business.tool_call_audit (request_id);
CREATE INDEX IF NOT EXISTS idx_tool_call_audit_created_at
    ON business.tool_call_audit (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_tool_call_audit_tool_result
    ON business.tool_call_audit (tool_name, result_code, created_at DESC);

COMMENT ON TABLE business.business_order IS 'Java 业务服务管理的订单查询视图数据';
COMMENT ON TABLE business.tool_call_audit IS 'Python 调用 Java Tool 的审计记录，不保存聊天原文';

-- 以后新增订单更新接口时，此触发器保证 updated_at 不会因调用方遗漏而失真。
CREATE OR REPLACE FUNCTION business.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_business_order_updated_at ON business.business_order;
CREATE TRIGGER trg_business_order_updated_at
    BEFORE UPDATE ON business.business_order
    FOR EACH ROW
    EXECUTE FUNCTION business.set_updated_at();
