-- 知识库主数据、审批、检索片段和可靠同步事件。
-- PostgreSQL 是唯一主数据源；Redis Search 只保存审批通过后的检索副本。

CREATE TABLE business.kb_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_code VARCHAR(64) NOT NULL,
    category_name VARCHAR(128) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    status SMALLINT NOT NULL DEFAULT 1,
    created_by VARCHAR(64) NOT NULL,
    updated_by VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_kb_category_code UNIQUE (category_code),
    CONSTRAINT ck_kb_category_status CHECK (status IN (0, 1))
);

CREATE TABLE business.kb_knowledge (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_code VARCHAR(64) NOT NULL,
    category_id BIGINT NOT NULL,
    current_version_id BIGINT,
    pending_version_id BIGINT,
    status SMALLINT NOT NULL DEFAULT 0,
    created_by VARCHAR(64) NOT NULL,
    updated_by VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lock_version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_kb_knowledge_code UNIQUE (knowledge_code),
    CONSTRAINT fk_kb_knowledge_category FOREIGN KEY (category_id)
        REFERENCES business.kb_category (id),
    CONSTRAINT ck_kb_knowledge_status CHECK (status IN (0, 1)),
    CONSTRAINT ck_kb_knowledge_lock_version CHECK (lock_version >= 0)
);

CREATE TABLE business.kb_knowledge_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_id BIGINT NOT NULL,
    version_no INTEGER NOT NULL,
    title VARCHAR(256) NOT NULL,
    content TEXT NOT NULL,
    tags VARCHAR(64)[] NOT NULL DEFAULT ARRAY[]::VARCHAR(64)[],
    intent_code VARCHAR(64),
    version_status SMALLINT NOT NULL DEFAULT 0,
    effective_at TIMESTAMPTZ NOT NULL,
    expired_at TIMESTAMPTZ,
    published_at TIMESTAMPTZ,
    created_by VARCHAR(64) NOT NULL,
    updated_by VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_kb_version_no UNIQUE (knowledge_id, version_no),
    CONSTRAINT uk_kb_version_id_knowledge UNIQUE (id, knowledge_id),
    CONSTRAINT fk_kb_version_knowledge FOREIGN KEY (knowledge_id)
        REFERENCES business.kb_knowledge (id),
    CONSTRAINT ck_kb_version_status CHECK (version_status IN (0, 1, 2, 3, 4)),
    CONSTRAINT ck_kb_version_time CHECK (expired_at IS NULL OR expired_at > effective_at)
);

ALTER TABLE business.kb_knowledge
    ADD CONSTRAINT fk_kb_knowledge_current_version
        FOREIGN KEY (current_version_id) REFERENCES business.kb_knowledge_version (id),
    ADD CONSTRAINT fk_kb_knowledge_pending_version
        FOREIGN KEY (pending_version_id) REFERENCES business.kb_knowledge_version (id);

CREATE TABLE business.kb_approval (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    approval_no VARCHAR(64) NOT NULL,
    knowledge_id BIGINT NOT NULL,
    version_id BIGINT NOT NULL,
    action_type SMALLINT NOT NULL,
    status SMALLINT NOT NULL DEFAULT 0,
    applicant_id VARCHAR(64) NOT NULL,
    approver_id VARCHAR(64),
    application_reason VARCHAR(1000),
    approval_comment VARCHAR(1000),
    rejection_reason VARCHAR(1000),
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_kb_approval_no UNIQUE (approval_no),
    CONSTRAINT fk_kb_approval_knowledge FOREIGN KEY (knowledge_id)
        REFERENCES business.kb_knowledge (id),
    CONSTRAINT fk_kb_approval_version_knowledge FOREIGN KEY (version_id, knowledge_id)
        REFERENCES business.kb_knowledge_version (id, knowledge_id),
    CONSTRAINT ck_kb_approval_action CHECK (action_type IN (1, 2, 3)),
    CONSTRAINT ck_kb_approval_status CHECK (status IN (0, 1, 2, 3)),
    CONSTRAINT ck_kb_approval_finished CHECK (
        (status = 0 AND finished_at IS NULL) OR
        (status <> 0 AND finished_at IS NOT NULL)
    )
);

CREATE UNIQUE INDEX uk_kb_approval_one_pending
    ON business.kb_approval (knowledge_id)
    WHERE status = 0;

CREATE TABLE business.kb_knowledge_chunk (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_id BIGINT NOT NULL,
    version_id BIGINT NOT NULL,
    chunk_no INTEGER NOT NULL,
    chunk_content TEXT NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    redis_key VARCHAR(256) NOT NULL,
    index_version INTEGER NOT NULL DEFAULT 1,
    sync_status SMALLINT NOT NULL DEFAULT 0,
    sync_error VARCHAR(1000),
    synced_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_kb_chunk_version_no UNIQUE (version_id, chunk_no),
    CONSTRAINT uk_kb_chunk_redis_key UNIQUE (redis_key),
    CONSTRAINT fk_kb_chunk_version_knowledge FOREIGN KEY (version_id, knowledge_id)
        REFERENCES business.kb_knowledge_version (id, knowledge_id),
    CONSTRAINT ck_kb_chunk_no CHECK (chunk_no >= 0),
    CONSTRAINT ck_kb_chunk_index_version CHECK (index_version > 0),
    CONSTRAINT ck_kb_chunk_sync_status CHECK (sync_status IN (0, 1, 2))
);

CREATE TABLE business.kb_operation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_id BIGINT NOT NULL,
    version_id BIGINT,
    approval_id BIGINT,
    operation_type SMALLINT NOT NULL,
    operator_id VARCHAR(64) NOT NULL,
    before_data JSONB,
    after_data JSONB,
    request_id VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_kb_log_knowledge FOREIGN KEY (knowledge_id)
        REFERENCES business.kb_knowledge (id),
    CONSTRAINT fk_kb_log_version FOREIGN KEY (version_id)
        REFERENCES business.kb_knowledge_version (id),
    CONSTRAINT fk_kb_log_approval FOREIGN KEY (approval_id)
        REFERENCES business.kb_approval (id)
);

CREATE TABLE business.kb_outbox_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(64) NOT NULL,
    knowledge_id BIGINT NOT NULL,
    version_id BIGINT NOT NULL,
    event_type SMALLINT NOT NULL,
    payload JSONB NOT NULL DEFAULT '{}'::JSONB,
    status SMALLINT NOT NULL DEFAULT 0,
    retry_count INTEGER NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_error VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMPTZ,
    CONSTRAINT uk_kb_outbox_event_id UNIQUE (event_id),
    CONSTRAINT fk_kb_outbox_knowledge FOREIGN KEY (knowledge_id)
        REFERENCES business.kb_knowledge (id),
    CONSTRAINT fk_kb_outbox_version_knowledge FOREIGN KEY (version_id, knowledge_id)
        REFERENCES business.kb_knowledge_version (id, knowledge_id),
    CONSTRAINT ck_kb_outbox_event_type CHECK (event_type IN (1, 2)),
    CONSTRAINT ck_kb_outbox_status CHECK (status IN (0, 1, 2, 3)),
    CONSTRAINT ck_kb_outbox_retry_count CHECK (retry_count >= 0)
);

CREATE INDEX idx_kb_knowledge_category ON business.kb_knowledge (category_id);
CREATE INDEX idx_kb_knowledge_status ON business.kb_knowledge (status);
CREATE INDEX idx_kb_version_knowledge_status
    ON business.kb_knowledge_version (knowledge_id, version_status);
CREATE INDEX idx_kb_version_tags ON business.kb_knowledge_version USING GIN (tags);
CREATE INDEX idx_kb_approval_status_submitted
    ON business.kb_approval (status, submitted_at DESC);
CREATE INDEX idx_kb_chunk_knowledge ON business.kb_knowledge_chunk (knowledge_id);
CREATE INDEX idx_kb_chunk_version ON business.kb_knowledge_chunk (version_id);
CREATE INDEX idx_kb_chunk_sync_status ON business.kb_knowledge_chunk (sync_status);
CREATE INDEX idx_kb_log_knowledge_created
    ON business.kb_operation_log (knowledge_id, created_at DESC);
CREATE INDEX idx_kb_outbox_pending
    ON business.kb_outbox_event (status, next_retry_at, id)
    WHERE status IN (0, 3);

-- 复用V1创建的更新时间函数，确保调用方漏写时数据库仍会维护updated_at。
CREATE TRIGGER trg_kb_category_updated_at
    BEFORE UPDATE ON business.kb_category
    FOR EACH ROW EXECUTE FUNCTION business.set_updated_at();
CREATE TRIGGER trg_kb_knowledge_updated_at
    BEFORE UPDATE ON business.kb_knowledge
    FOR EACH ROW EXECUTE FUNCTION business.set_updated_at();
CREATE TRIGGER trg_kb_version_updated_at
    BEFORE UPDATE ON business.kb_knowledge_version
    FOR EACH ROW EXECUTE FUNCTION business.set_updated_at();
CREATE TRIGGER trg_kb_approval_updated_at
    BEFORE UPDATE ON business.kb_approval
    FOR EACH ROW EXECUTE FUNCTION business.set_updated_at();
CREATE TRIGGER trg_kb_chunk_updated_at
    BEFORE UPDATE ON business.kb_knowledge_chunk
    FOR EACH ROW EXECUTE FUNCTION business.set_updated_at();

COMMENT ON TABLE business.kb_knowledge IS '知识稳定身份和当前/待审批版本指针';
COMMENT ON TABLE business.kb_knowledge_version IS '知识的不可变版本内容';
COMMENT ON TABLE business.kb_approval IS '新增、修改、停用审批单';
COMMENT ON TABLE business.kb_knowledge_chunk IS '已发布版本的检索切片与Redis同步状态';
COMMENT ON TABLE business.kb_outbox_event IS '审批事务内写入的Redis可靠同步事件';
