-- 原子分片在提交审批时即入库，审批通过后只补充Redis同步信息。
ALTER TABLE business.kb_knowledge_chunk
    ALTER COLUMN redis_key DROP NOT NULL;

COMMENT ON TABLE business.kb_knowledge_chunk IS
    '知识版本原子分片；审批前保存草稿，发布后补充Redis同步状态';

CREATE TABLE business.kb_knowledge_question (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_id BIGINT NOT NULL,
    version_id BIGINT NOT NULL,
    chunk_id BIGINT NOT NULL,
    question_no INTEGER NOT NULL,
    question_text TEXT NOT NULL,
    question_hash VARCHAR(64) NOT NULL,
    redis_key VARCHAR(256),
    sync_status SMALLINT NOT NULL DEFAULT 0,
    sync_error VARCHAR(1000),
    synced_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_kb_question_chunk_no UNIQUE (chunk_id, question_no),
    CONSTRAINT uk_kb_question_redis_key UNIQUE (redis_key),
    CONSTRAINT fk_kb_question_chunk FOREIGN KEY (chunk_id)
        REFERENCES business.kb_knowledge_chunk (id) ON DELETE CASCADE,
    CONSTRAINT fk_kb_question_version_knowledge FOREIGN KEY (version_id, knowledge_id)
        REFERENCES business.kb_knowledge_version (id, knowledge_id),
    CONSTRAINT ck_kb_question_no CHECK (question_no >= 0),
    CONSTRAINT ck_kb_question_text CHECK (length(btrim(question_text)) > 0),
    CONSTRAINT ck_kb_question_sync_status CHECK (sync_status IN (0, 1, 2))
);

CREATE INDEX idx_kb_question_version
    ON business.kb_knowledge_question (version_id, chunk_id, question_no);
CREATE INDEX idx_kb_question_sync_status
    ON business.kb_knowledge_question (sync_status);

CREATE TRIGGER trg_kb_question_updated_at
    BEFORE UPDATE ON business.kb_knowledge_question
    FOR EACH ROW EXECUTE FUNCTION business.set_updated_at();

COMMENT ON TABLE business.kb_knowledge_question IS
    '原子分片的标准问法；每条问法独立生成向量但返回所属分片内容';
