-- 为积分、奖励、会员权益和退款查询提供可替换的业务数据表。
-- 当前插入少量演示数据用于联调；接入正式业务系统后保留Tool契约，替换数据同步来源即可。

CREATE TABLE IF NOT EXISTS business.customer_points_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL,
    points_balance INTEGER NOT NULL DEFAULT 0,
    expiring_points INTEGER NOT NULL DEFAULT 0,
    expire_date DATE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_customer_points_user UNIQUE (user_id),
    CONSTRAINT ck_customer_points_balance CHECK (points_balance >= 0),
    CONSTRAINT ck_customer_expiring_points CHECK (
        expiring_points >= 0 AND expiring_points <= points_balance
    )
);

CREATE TABLE IF NOT EXISTS business.customer_reward_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reward_no VARCHAR(64) NOT NULL,
    user_id VARCHAR(64) NOT NULL,
    activity_name VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL,
    expected_at TIMESTAMPTZ,
    issued_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_customer_reward_no UNIQUE (reward_no),
    CONSTRAINT ck_customer_reward_status CHECK (
        status IN ('PROCESSING', 'ISSUED', 'FAILED', 'EXPIRED')
    )
);

CREATE INDEX IF NOT EXISTS idx_customer_reward_user_activity
    ON business.customer_reward_record (user_id, activity_name, updated_at DESC)
    WHERE deleted = FALSE;

CREATE TABLE IF NOT EXISTS business.customer_member_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL,
    level_code VARCHAR(32) NOT NULL,
    level_name VARCHAR(64) NOT NULL,
    growth_value INTEGER NOT NULL DEFAULT 0,
    benefits_text VARCHAR(1000) NOT NULL,
    valid_until DATE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_customer_member_user UNIQUE (user_id),
    CONSTRAINT ck_customer_growth_value CHECK (growth_value >= 0)
);

CREATE TABLE IF NOT EXISTS business.customer_refund_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refund_no VARCHAR(64) NOT NULL,
    order_no VARCHAR(64) NOT NULL,
    user_id VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    refund_amount NUMERIC(12, 2) NOT NULL,
    expected_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_customer_refund_no UNIQUE (refund_no),
    CONSTRAINT ck_customer_refund_status CHECK (
        status IN ('APPLIED', 'PROCESSING', 'APPROVED', 'REFUNDED', 'REJECTED', 'CLOSED')
    ),
    CONSTRAINT ck_customer_refund_amount CHECK (refund_amount >= 0)
);

CREATE INDEX IF NOT EXISTS idx_customer_refund_user_order
    ON business.customer_refund_record (user_id, order_no, updated_at DESC)
    WHERE deleted = FALSE;

-- 演示账号与Python默认登录用户一致，便于页面直接验证四个Tool。
INSERT INTO business.customer_points_account (
    user_id, points_balance, expiring_points, expire_date
)
VALUES ('demo-user-001', 1280, 120, DATE '2026-12-31')
ON CONFLICT (user_id) DO NOTHING;

INSERT INTO business.customer_reward_record (
    reward_no, user_id, activity_name, status, expected_at
)
VALUES (
    'REWARD_20260809001', 'demo-user-001', '消费返现活动', 'PROCESSING',
    CURRENT_TIMESTAMP + INTERVAL '3 days'
)
ON CONFLICT (reward_no) DO NOTHING;

INSERT INTO business.customer_member_profile (
    user_id, level_code, level_name, growth_value, benefits_text, valid_until
)
VALUES (
    'demo-user-001', 'GOLD', '黄金会员', 3680,
    '每月2张运费券、会员专属优惠券、生日月礼包', DATE '2027-08-09'
)
ON CONFLICT (user_id) DO NOTHING;

INSERT INTO business.customer_refund_record (
    refund_no, order_no, user_id, status, refund_amount, expected_at
)
VALUES (
    'REFUND_20260809001', 'ORDER_20260809001', 'demo-user-001',
    'PROCESSING', 199.00, CURRENT_TIMESTAMP + INTERVAL '2 days'
)
ON CONFLICT (refund_no) DO NOTHING;

COMMENT ON TABLE business.customer_points_account IS '用户实时积分账户查询数据';
COMMENT ON TABLE business.customer_reward_record IS '活动奖励发放记录';
COMMENT ON TABLE business.customer_member_profile IS '会员等级和有效权益摘要';
COMMENT ON TABLE business.customer_refund_record IS '订单退款处理记录';
