-- 售后退款试算只读取订单商品和成交价格快照，不创建退款单，也不调用支付系统。
-- 正式接入订单中心后，可以通过同步任务维护这两张只读投影表，Tool契约无需变化。

CREATE TABLE IF NOT EXISTS business.order_refund_pricing (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(64) NOT NULL,
    goods_amount NUMERIC(12, 2) NOT NULL,
    shipping_fee NUMERIC(12, 2) NOT NULL DEFAULT 0,
    order_discount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    coupon_discount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    points_discount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_order_refund_pricing_order UNIQUE (order_no),
    CONSTRAINT ck_order_refund_pricing_amounts CHECK (
        goods_amount > 0
        AND shipping_fee >= 0
        AND order_discount >= 0
        AND coupon_discount >= 0
        AND points_discount >= 0
        AND order_discount + coupon_discount + points_discount <= goods_amount
    )
);

CREATE TABLE IF NOT EXISTS business.order_refund_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(64) NOT NULL,
    sku_id VARCHAR(64) NOT NULL,
    sku_name VARCHAR(200) NOT NULL,
    unit_price NUMERIC(12, 2) NOT NULL,
    purchased_quantity INTEGER NOT NULL,
    refundable_quantity INTEGER NOT NULL,
    returnable BOOLEAN NOT NULL DEFAULT TRUE,
    after_sale_deadline TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_order_refund_item_order_sku UNIQUE (order_no, sku_id),
    CONSTRAINT ck_order_refund_item_price CHECK (unit_price >= 0),
    CONSTRAINT ck_order_refund_item_quantity CHECK (
        purchased_quantity > 0
        AND refundable_quantity >= 0
        AND refundable_quantity <= purchased_quantity
    )
);

CREATE INDEX IF NOT EXISTS idx_order_refund_item_order
    ON business.order_refund_item (order_no, sku_id)
    WHERE deleted = FALSE;

-- 演示订单与Python默认登录用户一致，包含两个商品及满减、优惠券、积分抵扣。
INSERT INTO business.business_order (
    order_no, user_id, status, logistics_text, expected_progress
)
VALUES (
    'ORDER_20260809001', 'demo-user-001', 'DELIVERED',
    '订单已签收', '已完成'
)
ON CONFLICT (order_no) DO NOTHING;

INSERT INTO business.order_refund_pricing (
    order_no, goods_amount, shipping_fee,
    order_discount, coupon_discount, points_discount
)
VALUES (
    'ORDER_20260809001', 397.00, 10.00, 40.00, 20.00, 10.00
)
ON CONFLICT (order_no) DO NOTHING;

INSERT INTO business.order_refund_item (
    order_no, sku_id, sku_name, unit_price,
    purchased_quantity, refundable_quantity, returnable, after_sale_deadline
)
VALUES
    (
        'ORDER_20260809001', 'SKU_PHONE_CASE', '防摔手机壳', 99.00,
        2, 2, TRUE, TIMESTAMPTZ '2027-12-31 23:59:59+08'
    ),
    (
        'ORDER_20260809001', 'SKU_CHARGER', '65W快充充电器', 199.00,
        1, 1, TRUE, TIMESTAMPTZ '2027-12-31 23:59:59+08'
    )
ON CONFLICT (order_no, sku_id) DO NOTHING;

COMMENT ON TABLE business.order_refund_pricing IS '退款试算使用的订单成交价格快照';
COMMENT ON TABLE business.order_refund_item IS '退款试算使用的订单商品与可售后数量投影';
