-- 退款报价快照、售后申请和异步支付任务使用独立表，避免一个状态字段承担多个职责。

CREATE TABLE IF NOT EXISTS business.refund_quote_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote_token VARCHAR(64) NOT NULL,
    user_id VARCHAR(64) NOT NULL,
    order_no VARCHAR(64) NOT NULL,
    reason_code VARCHAR(32) NOT NULL,
    received BOOLEAN NOT NULL,
    refund_items_json TEXT NOT NULL,
    available_methods_json TEXT NOT NULL,
    refund_amount NUMERIC(12, 2) NOT NULL,
    goods_amount NUMERIC(12, 2) NOT NULL,
    discount_deduction NUMERIC(12, 2) NOT NULL,
    points_deduction NUMERIC(12, 2) NOT NULL,
    shipping_refund NUMERIC(12, 2) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_refund_quote_token UNIQUE (quote_token),
    CONSTRAINT ck_refund_quote_status CHECK (status IN ('ACTIVE', 'USED', 'EXPIRED')),
    CONSTRAINT ck_refund_quote_amount CHECK (
        refund_amount >= 0 AND goods_amount >= 0
        AND discount_deduction >= 0 AND points_deduction >= 0
        AND shipping_refund >= 0
    )
);

CREATE INDEX IF NOT EXISTS idx_refund_quote_user_token
    ON business.refund_quote_snapshot (user_id, quote_token)
    WHERE deleted = FALSE;

CREATE TABLE IF NOT EXISTS business.after_sales_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    after_sales_no VARCHAR(64) NOT NULL,
    quote_token VARCHAR(64) NOT NULL,
    idempotency_key VARCHAR(64) NOT NULL,
    user_id VARCHAR(64) NOT NULL,
    order_no VARCHAR(64) NOT NULL,
    method VARCHAR(32) NOT NULL,
    reason_code VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    risk_level VARCHAR(16) NOT NULL,
    review_required BOOLEAN NOT NULL,
    refund_amount NUMERIC(12, 2) NOT NULL,
    refund_items_json TEXT NOT NULL,
    payment_transaction_no VARCHAR(64),
    reviewed_by BIGINT,
    reviewed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_after_sales_no UNIQUE (after_sales_no),
    CONSTRAINT uk_after_sales_quote UNIQUE (quote_token),
    CONSTRAINT uk_after_sales_idempotency UNIQUE (user_id, idempotency_key),
    CONSTRAINT ck_after_sales_status CHECK (status IN (
        'PENDING_REVIEW', 'PAYMENT_PROCESSING', 'REFUNDED',
        'REJECTED', 'PAYMENT_FAILED', 'CLOSED'
    )),
    CONSTRAINT ck_after_sales_risk CHECK (risk_level IN ('LOW', 'HIGH')),
    CONSTRAINT ck_after_sales_amount CHECK (refund_amount >= 0)
);

CREATE INDEX IF NOT EXISTS idx_after_sales_user_order
    ON business.after_sales_order (user_id, order_no, created_at DESC)
    WHERE deleted = FALSE;

CREATE TABLE IF NOT EXISTS business.payment_refund_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_no VARCHAR(64) NOT NULL,
    after_sales_no VARCHAR(64) NOT NULL,
    refund_amount NUMERIC(12, 2) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    attempts INTEGER NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    payment_transaction_no VARCHAR(64),
    last_error VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMPTZ,
    CONSTRAINT uk_payment_refund_task_no UNIQUE (task_no),
    CONSTRAINT uk_payment_refund_after_sales UNIQUE (after_sales_no),
    CONSTRAINT ck_payment_refund_task_status CHECK (
        status IN ('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED')
    ),
    CONSTRAINT ck_payment_refund_task_amount CHECK (refund_amount >= 0),
    CONSTRAINT ck_payment_refund_task_attempts CHECK (attempts >= 0)
);

CREATE INDEX IF NOT EXISTS idx_payment_refund_task_poll
    ON business.payment_refund_task (status, next_retry_at, id)
    WHERE status IN ('PENDING', 'FAILED');

DROP TRIGGER IF EXISTS trg_refund_quote_updated_at ON business.refund_quote_snapshot;
CREATE TRIGGER trg_refund_quote_updated_at
    BEFORE UPDATE ON business.refund_quote_snapshot
    FOR EACH ROW EXECUTE FUNCTION business.set_updated_at();

DROP TRIGGER IF EXISTS trg_after_sales_updated_at ON business.after_sales_order;
CREATE TRIGGER trg_after_sales_updated_at
    BEFORE UPDATE ON business.after_sales_order
    FOR EACH ROW EXECUTE FUNCTION business.set_updated_at();

DROP TRIGGER IF EXISTS trg_payment_refund_task_updated_at ON business.payment_refund_task;
CREATE TRIGGER trg_payment_refund_task_updated_at
    BEFORE UPDATE ON business.payment_refund_task
    FOR EACH ROW EXECUTE FUNCTION business.set_updated_at();

COMMENT ON TABLE business.refund_quote_snapshot IS '退款试算快照，quoteToken默认十分钟有效';
COMMENT ON TABLE business.after_sales_order IS '用户确认后创建的正式售后申请';
COMMENT ON TABLE business.payment_refund_task IS '异步调用支付退款网关的任务表';
