-- 问题学习模块只把 PostgreSQL 作为事实库；Redis 不保存投诉、反馈或聚类统计。
CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;
CREATE SCHEMA IF NOT EXISTS learning;

-- 每一次明确触发都保存为独立信号。source_type 使用数字枚举，代码负责转换名称。
CREATE TABLE learning.learning_signal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signal_key VARCHAR(160) NOT NULL,
    source_type SMALLINT NOT NULL,
    source_id VARCHAR(64) NOT NULL,
    conversation_id VARCHAR(36) NOT NULL,
    trigger_message_id VARCHAR(36) NOT NULL,
    target_assistant_message_id VARCHAR(36),
    user_id VARCHAR(64) NOT NULL,
    question_text TEXT NOT NULL,
    answer_text TEXT,
    intent_code VARCHAR(64),
    confidence REAL,
    tool_name VARCHAR(128),
    failure_code VARCHAR(128),
    process_status SMALLINT NOT NULL DEFAULT 0,
    retry_count INTEGER NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    error_message VARCHAR(1000),
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMPTZ,
    CONSTRAINT uk_learning_signal_key UNIQUE (signal_key),
    CONSTRAINT ck_learning_signal_source CHECK (source_type IN (1, 2, 3, 4, 5, 6)),
    CONSTRAINT ck_learning_signal_status CHECK (process_status IN (0, 1, 2, 3, 4)),
    CONSTRAINT ck_learning_signal_retry CHECK (retry_count >= 0)
);

-- 一个 problem 代表一簇语义相同的问题，centroid_embedding 用于后续样本归类。
CREATE TABLE learning.learning_problem (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_code VARCHAR(64) NOT NULL,
    representative_question TEXT NOT NULL,
    problem_summary TEXT NOT NULL,
    intent_code VARCHAR(64),
    centroid_embedding HALFVEC(2048) NOT NULL,
    embedding_model VARCHAR(128) NOT NULL,
    occurrence_count INTEGER NOT NULL DEFAULT 1,
    affected_user_count INTEGER NOT NULL DEFAULT 1,
    conversation_count INTEGER NOT NULL DEFAULT 1,
    priority SMALLINT NOT NULL DEFAULT 1,
    status SMALLINT NOT NULL DEFAULT 0,
    first_seen_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL,
    created_by VARCHAR(64) NOT NULL DEFAULT 'python-learning-worker',
    updated_by VARCHAR(64) NOT NULL DEFAULT 'python-learning-worker',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMPTZ,
    CONSTRAINT uk_learning_problem_code UNIQUE (problem_code),
    CONSTRAINT ck_learning_problem_priority CHECK (priority IN (1, 2, 3)),
    CONSTRAINT ck_learning_problem_status CHECK (status IN (0, 1, 2, 3, 4, 5))
);

-- 当前版本一个信号提取一个原子问题；保留独立表便于以后一个投诉拆成多个问题。
CREATE TABLE learning.learning_sample (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signal_id BIGINT NOT NULL,
    problem_id BIGINT NOT NULL,
    sample_no INTEGER NOT NULL DEFAULT 1,
    root_question TEXT NOT NULL,
    original_answer TEXT,
    extraction_method SMALLINT NOT NULL DEFAULT 1,
    extraction_confidence REAL NOT NULL DEFAULT 1.0,
    embedding HALFVEC(2048) NOT NULL,
    embedding_model VARCHAR(128) NOT NULL,
    cluster_distance REAL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_learning_sample_signal_no UNIQUE (signal_id, sample_no),
    CONSTRAINT fk_learning_sample_signal FOREIGN KEY (signal_id)
        REFERENCES learning.learning_signal (id),
    CONSTRAINT fk_learning_sample_problem FOREIGN KEY (problem_id)
        REFERENCES learning.learning_problem (id),
    CONSTRAINT ck_learning_sample_method CHECK (extraction_method IN (1, 2, 3)),
    CONSTRAINT ck_learning_sample_confidence CHECK (
        extraction_confidence >= 0 AND extraction_confidence <= 1
    )
);

CREATE INDEX idx_learning_signal_pending
    ON learning.learning_signal (process_status, next_retry_at, id)
    WHERE process_status IN (0, 3);
CREATE INDEX idx_learning_signal_conversation
    ON learning.learning_signal (conversation_id, occurred_at DESC);
CREATE INDEX idx_learning_signal_source_time
    ON learning.learning_signal (source_type, occurred_at DESC);
CREATE INDEX idx_learning_problem_status_time
    ON learning.learning_problem (status, last_seen_at DESC);
CREATE INDEX idx_learning_sample_problem
    ON learning.learning_sample (problem_id, processed_at DESC);

-- 2048 维超过 vector 索引的 2000 维上限，因此使用 halfvec 的余弦 HNSW 索引。
CREATE INDEX idx_learning_problem_centroid_hnsw
    ON learning.learning_problem
    USING hnsw (centroid_embedding halfvec_cosine_ops);
CREATE INDEX idx_learning_sample_embedding_hnsw
    ON learning.learning_sample
    USING hnsw (embedding halfvec_cosine_ops);

CREATE TRIGGER trg_learning_problem_updated_at
    BEFORE UPDATE ON learning.learning_problem
    FOR EACH ROW EXECUTE FUNCTION business.set_updated_at();

COMMENT ON TABLE learning.learning_signal IS '没帮助、差评、申请人工、投诉、Tool失败和RAG无命中的原始信号';
COMMENT ON TABLE learning.learning_problem IS '经过向量相似归类后的问题簇';
COMMENT ON TABLE learning.learning_sample IS '问题信号提取并向量化后的原子样本';
